import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/shared/header";
import { Providers } from "@/components/shared/providers";

const alexC = localFont({
  src: "./fonts/AlexC.woff",
  variable: "--font-alexC",
  weight: "400",
});
const montserratMedium = localFont({
  src: "./fonts/MontserratMedium.woff",
  variable: "--font-montserrat-medium",
  weight: "400",
});
const montserratBold = localFont({
  src: "./fonts/MontserratBold.woff",
  variable: "--font-montserrat-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "STAY - Школа театрального искусства",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${alexC.variable} ${montserratMedium.variable} ${montserratBold.variable} antialiased`}
      >
        <main className="min-h-screen">
          
          <Providers>
            <Header />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}